### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf-storefront#1]
Store is starting to look great. Let's make it better.

**New header structure** 
(put our menu to the challenge with a few people and got feedback) we had some industry specific term (white label is not super highly understood in usa) we favor USA / Canada native terms or more understandable for them. 

![Screenshot 2024-08-19 at 15 13 31](https://github.com/user-attachments/assets/5bf226a4-2588-4b2b-ab0e-f20d8fa627cc)

Basically ( Shop all ) leads to our full index unfiltered.  | Unbranded tags to our collection of white-label tags | Custom branding collection of branded products | Support should lead to a page either in shopify or our marketing site with just FAQs. (Not sure about this yet) - considering where we are at. I rather use / store all of this on the shopify CMS.

 **Account Icon | Search Icon | Shopping cart** 
Account icon, it would be cool if we could detect if user is signed up and swap it? For the rest they can stay as they are. The consecutive counting up of the cart item numbers is nice to have but not a must. 

![improvedheader](https://github.com/user-attachments/assets/8d5b6a6a-798e-4855-8aa7-1931264a5a8f)

**Comment by carlosvirreira** [comment]
![Frame 48](https://github.com/user-attachments/assets/753d1ef0-1fb6-442a-9e33-8509fa9ea106)

Suggestions for collection page(s) header. 

Assets attached. 

For smaller screen sizes / mobile / we can not show the asset. On mobile we should prio performance above all imo.

<img width="923" alt="headercategorypages" src="https://github.com/user-attachments/assets/23f05182-844c-4549-bd44-a4f1fa19f21a">

<img width="1212" alt="headercategorypagescombinedwithtext" src="https://github.com/user-attachments/assets/5d2eb749-16ef-4173-93cd-d725aef4fd91">

**Comment by carlosvirreira** [comment]
@DonKoko 

We need to change this 'default title' for all whitelabel products.

![Screenshot 2024-10-21 at 13 16 15](https://github.com/user-attachments/assets/f07f5d2f-0b71-44d3-9ba0-b785c43813a5)

On branded they work fine. 

![Uploading Screenshot 2024-10-21 at 13.17.07.jpg…]()

---

https://store.shelf.nu/products/rectangle-custom-asset-labels?Bundle=4+sheets+%28176%29
On this listing, our calculation of sheets and price is working well.

We need to adjust for:

- [ ] https://store.shelf.nu/products/large-custom-asset-labels?Bundle=Bundle+of+1+sheet
- [ ] https://store.shelf.nu/products/medium-custom-asset-labels?Bundle=Bundle+of+1+sheet

---- 

We have alignment issues with one field of FAQ

![Screenshot 2024-10-21 at 13 19 18](https://github.com/user-attachments/assets/f577fd16-7067-4ac6-9900-4f2a6b5f4e29)

**Comment by DonKoko** [comment]
@carlosvirreira the "Default title" and the alignment bugs are solved.

This i dont understand what you mean:

> https://store.shelf.nu/products/rectangle-custom-asset-labels?Bundle=4+sheets+%28176%29
> On this listing, our calculation of sheets and price is working well.
> 
> We need to adjust for:
> 
> https://store.shelf.nu/products/large-custom-asset-labels?Bundle=Bundle+of+1+sheet
> https://store.shelf.nu/products/medium-custom-asset-labels?Bundle=Bundle+of+1+sheet

**Comment by carlosvirreira** [comment]
@DonKoko 

I refer to this calculation here. 

![Screenshot 2024-10-24 at 16 12 42](https://github.com/user-attachments/assets/75a8b217-4438-4c7a-a4c0-4ada6dd91b23)

**Comment by carlosvirreira** [comment]
Also we went a bit Dutch in here and it should read "checkout" instead of "chekout"

![Screenshot 2024-10-24 at 16 14 58](https://github.com/user-attachments/assets/7d2d7af7-3b17-4660-83d2-2a2357254cce)

**Comment by carlosvirreira** [comment]
https://github.com/user-attachments/assets/95ae2058-1583-4c9d-abbb-b1bd7f36ffee

Signing out on Safari leads to a cloudflare link

**Comment by DonKoko** [comment]
All the points above are resolved and deployed.
