### ISSUE TITLE
changing quantity issue (non bundled products)

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf-storefront#5]
user reported that you cannot get 2 or more sheets of a simple product because the quantity buttons reset back to 1

https://github.com/user-attachments/assets/1f642a13-32a4-461c-a632-3feb15adb31f

**Comment by DonKoko** [comment]
Was content issue. WE were out of stock and didnt allow backorders. Has been resolved by allowing backorders.
